### ISSUE TITLE
Fix in "install.xml": DEFAULT incorrectly set for "rp_orderid"

### ISSUE THREAD

**Issue by eduardokraus** [santoshndev/moodle-paygw_razorpay#1]
In the install.xml file, the rp_orderid attribute has a value set in DEFAULT, but it should be in COMMENT.

![Captura de Tela 2024-11-16 às 08 31 58](https://github.com/user-attachments/assets/23d2684b-94e6-4e9e-b275-b2f240cef63a)

**Comment by santoshndev** [comment]
Thanks @eduardokraus for the review.
I have fixed the issue
